# Generated by Django 4.2.17 on 2025-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_available_count',
            field=models.IntegerField(default=''),
        ),
    ]
