# Generated by Django 4.2.17 on 2025-01-14 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
