# Generated by Django 4.2.17 on 2025-01-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_checkoutaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
